stages:
  - test
  - build
  - deploy

deploy_test:
  stage: test
  script: 
#    - echo "Deploy to staging server"
#    - echo "Running tests, check de root"
#    - echo $DEPLOYER_PRIVATE_KEY
#    - ssh -p22 root@varnish-d1.cepal.org "cd /etc/varnish  && varnishd -C -f default.vcl"
  environment:
    name: staging
    url: http://varnish-d1.cepal.org
  only:
  - master

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: http://varnish-q1.cepal.org
  only:
  - master

